---
include:
  # Scanner - Non-Touch Mode (display only, no swipe navigation)
  - board: kblade//zmk
    shield: prospector_scanner
    artifact-name: prospector_dongle

  # # Settings reset utility
  # - board: kblade//zmk
  #   shield: settings_reset
